/**
 * Generator for src/data/deals.json.
 * Run with: node seed/generate-deals.js
 *
 * Generates 50 total demo deal entities representing all stages:
 * - OPEN
 * - PENDING_APPROVAL (SALES_MANAGER, FINANCE)
 * - FULFILLED (with multi-warehouse split)
 * - SUBSCRIBED (SaaS Cloud subscriptions with seats)
 * - REJECTED (High-risk / policy violation)
 *
 * Across all health categories:
 * - HEALTHY
 * - AT_RISK (flagged by risk scoring engine)
 * - STALLED (inactive 5+ days)
 * - CLOSED_LOST (rejected / lost)
 */
const fs = require("fs");
const path = require("path");

const products = require("../src/data/products.json");
const priceOf = (id) => {
  const p = products.find((p) => p.id === id);
  if (!p) throw new Error(`Product not found: ${id}`);
  return p.unitPrice;
};
const nameOf = (id) => {
  const p = products.find((p) => p.id === id);
  if (!p) throw new Error(`Product not found: ${id}`);
  return p.name;
};

function lineItems(items) {
  return items.map(({ productId, qty }) => ({
    productId,
    name: nameOf(productId),
    qty,
    unitPrice: priceOf(productId),
  }));
}

function grossValue(items) {
  return items.reduce((sum, { productId, qty }) => sum + priceOf(productId) * qty, 0);
}

function netValue(items, discountPercent) {
  const gross = grossValue(items);
  return Math.round(gross * (1 - discountPercent / 100));
}

const raw = [
  // --- Anchors 001 to 016 (Preserved for compatibility with existing demo script & tests) ---
  {
    id: "DEMO-DEAL-001",
    customerId: "DEMO-CUST-004",
    salesRepId: "DEMO-REP-004",
    items: [{ productId: "DEMO-PROD-002", qty: 10 }],
    discountPercent: 8,
    stage: "OPEN",
    approvalStage: "NONE",
    riskScore: null,
    riskLevel: null,
    riskExplanation: null,
    createdDaysAgo: 10,
    lastActivityDaysAgo: 1,
    upsellOpportunity: true,
    suggestedUpsellProducts: ["DEMO-PROD-006"],
    scenarioTags: ["healthy", "upsell-candidate"],
  },
  {
    id: "DEMO-DEAL-002",
    customerId: "DEMO-CUST-001",
    salesRepId: "DEMO-REP-001",
    items: [{ productId: "DEMO-PROD-001", qty: 5 }],
    discountPercent: 25,
    stage: "PENDING_APPROVAL",
    approvalStage: "SALES_MANAGER",
    riskScore: 82,
    riskLevel: "HIGH",
    riskExplanation:
      "Discount is significantly above the sales representative's historical average.",
    createdDaysAgo: 6,
    lastActivityDaysAgo: 0,
    upsellOpportunity: false,
    suggestedUpsellProducts: [],
    scenarioTags: ["high-discount", "at-risk", "approval-required", "PRIMARY_DEMO"],
  },
  {
    id: "DEMO-DEAL-003",
    customerId: "DEMO-CUST-003",
    salesRepId: "DEMO-REP-003",
    items: [{ productId: "DEMO-PROD-004", qty: 20 }],
    discountPercent: 10,
    stage: "OPEN",
    approvalStage: "NONE",
    riskScore: null,
    riskLevel: "LOW",
    riskExplanation: null,
    createdDaysAgo: 15,
    lastActivityDaysAgo: 8,
    upsellOpportunity: false,
    suggestedUpsellProducts: [],
    scenarioTags: ["stalled", "SECONDARY_DEMO"],
  },
  {
    id: "DEMO-DEAL-004",
    customerId: "DEMO-CUST-002",
    salesRepId: "DEMO-REP-002",
    items: [
      { productId: "DEMO-PROD-001", qty: 10 },
      { productId: "DEMO-PROD-005", qty: 10 },
    ],
    discountPercent: 12,
    stage: "OPEN",
    approvalStage: "NONE",
    riskScore: null,
    riskLevel: "LOW",
    riskExplanation: null,
    createdDaysAgo: 20,
    lastActivityDaysAgo: 2,
    upsellOpportunity: false,
    suggestedUpsellProducts: [],
    scenarioTags: ["large-value", "healthy"],
  },
  {
    id: "DEMO-DEAL-005",
    customerId: "DEMO-CUST-002",
    salesRepId: "DEMO-REP-002",
    items: [{ productId: "DEMO-PROD-003", qty: 30 }],
    discountPercent: 22,
    stage: "PENDING_APPROVAL",
    approvalStage: "SALES_MANAGER",
    riskScore: 65,
    riskLevel: "MEDIUM",
    riskExplanation:
      "Discount is notably above the sales representative's historical average, though within an approvable range.",
    createdDaysAgo: 5,
    lastActivityDaysAgo: 1,
    upsellOpportunity: false,
    suggestedUpsellProducts: [],
    scenarioTags: ["at-risk", "approval-required"],
  },
  {
    id: "DEMO-DEAL-006",
    customerId: "DEMO-CUST-004",
    salesRepId: "DEMO-REP-004",
    items: [{ productId: "DEMO-PROD-002", qty: 15 }],
    discountPercent: 9,
    stage: "OPEN",
    approvalStage: "NONE",
    riskScore: null,
    riskLevel: null,
    riskExplanation: null,
    createdDaysAgo: 12,
    lastActivityDaysAgo: 3,
    upsellOpportunity: true,
    suggestedUpsellProducts: ["DEMO-PROD-006", "DEMO-PROD-005"],
    scenarioTags: ["healthy", "upsell-candidate", "SECONDARY_DEMO"],
  },
  {
    id: "DEMO-DEAL-007",
    customerId: "DEMO-CUST-003",
    salesRepId: "DEMO-REP-003",
    items: [{ productId: "DEMO-PROD-003", qty: 100 }],
    discountPercent: 10,
    stage: "FULFILLED",
    approvalStage: "NONE",
    riskScore: null,
    riskLevel: null,
    riskExplanation: null,
    createdDaysAgo: 25,
    lastActivityDaysAgo: 4,
    upsellOpportunity: false,
    suggestedUpsellProducts: [],
    warehouseSplit: [
      { warehouseId: "DEMO-WH-001", name: "Warehouse A", unitsAllocated: 60 },
      { warehouseId: "DEMO-WH-002", name: "Warehouse B", unitsAllocated: 40 },
    ],
    scenarioTags: ["warehouse-fulfillment"],
  },
  {
    id: "DEMO-DEAL-008",
    customerId: "DEMO-CUST-004",
    salesRepId: "DEMO-REP-004",
    items: [{ productId: "DEMO-PROD-004", qty: 50 }],
    discountPercent: 5,
    stage: "SUBSCRIBED",
    approvalStage: "NONE",
    riskScore: null,
    riskLevel: null,
    riskExplanation: null,
    createdDaysAgo: 30,
    lastActivityDaysAgo: 5,
    upsellOpportunity: false,
    suggestedUpsellProducts: [],
    subscription: {
      planName: "Cloud Subscription - Annual",
      billingCycle: "MONTHLY",
      seats: 50,
      prorationNote:
        "Mid-cycle seat changes are prorated by Santhosh's subscription/billing service.",
    },
    scenarioTags: ["subscription"],
  },
  {
    id: "DEMO-DEAL-009",
    customerId: "DEMO-CUST-001",
    salesRepId: "DEMO-REP-001",
    items: [{ productId: "DEMO-PROD-001", qty: 3 }],
    discountPercent: 15,
    stage: "FULFILLED",
    approvalStage: "APPROVED",
    riskScore: 55,
    riskLevel: "MEDIUM",
    riskExplanation:
      "Discount was moderately above the sales representative's historical average; approved after manager review.",
    createdDaysAgo: 40,
    lastActivityDaysAgo: 20,
    upsellOpportunity: false,
    suggestedUpsellProducts: [],
    warehouseSplit: [
      { warehouseId: "DEMO-WH-001", name: "Warehouse A", unitsAllocated: 2 },
      { warehouseId: "DEMO-WH-002", name: "Warehouse B", unitsAllocated: 1 },
    ],
    scenarioTags: ["completed-full-flow"],
  },
  {
    id: "DEMO-DEAL-010",
    customerId: "DEMO-CUST-002",
    salesRepId: "DEMO-REP-002",
    items: [{ productId: "DEMO-PROD-002", qty: 8 }],
    discountPercent: 12,
    stage: "OPEN",
    approvalStage: "NONE",
    riskScore: null,
    riskLevel: null,
    riskExplanation: null,
    createdDaysAgo: 8,
    lastActivityDaysAgo: 2,
    upsellOpportunity: true,
    suggestedUpsellProducts: ["DEMO-PROD-006"],
    scenarioTags: ["healthy", "upsell-candidate"],
  },
  {
    id: "DEMO-DEAL-011",
    customerId: "DEMO-CUST-003",
    salesRepId: "DEMO-REP-003",
    items: [{ productId: "DEMO-PROD-005", qty: 5 }],
    discountPercent: 7,
    stage: "OPEN",
    approvalStage: "NONE",
    riskScore: null,
    riskLevel: null,
    riskExplanation: null,
    createdDaysAgo: 9,
    lastActivityDaysAgo: 1,
    upsellOpportunity: false,
    suggestedUpsellProducts: [],
    scenarioTags: ["healthy"],
  },
  {
    id: "DEMO-DEAL-012",
    customerId: "DEMO-CUST-001",
    salesRepId: "DEMO-REP-004",
    items: [{ productId: "DEMO-PROD-003", qty: 12 }],
    discountPercent: 11,
    stage: "OPEN",
    approvalStage: "NONE",
    riskScore: null,
    riskLevel: null,
    riskExplanation: null,
    createdDaysAgo: 14,
    lastActivityDaysAgo: 3,
    upsellOpportunity: false,
    suggestedUpsellProducts: [],
    scenarioTags: ["healthy"],
  },
  {
    id: "DEMO-DEAL-013",
    customerId: "DEMO-CUST-004",
    salesRepId: "DEMO-REP-004",
    items: [{ productId: "DEMO-PROD-001", qty: 2 }],
    discountPercent: 10,
    stage: "PENDING_APPROVAL",
    approvalStage: "FINANCE",
    riskScore: 30,
    riskLevel: "LOW",
    riskExplanation:
      "Discount is in line with the sales representative's historical average; approval required due to deal value, not risk.",
    createdDaysAgo: 4,
    lastActivityDaysAgo: 1,
    upsellOpportunity: false,
    suggestedUpsellProducts: [],
    scenarioTags: ["approval-required", "value-threshold"],
  },
  {
    id: "DEMO-DEAL-014",
    customerId: "DEMO-CUST-002",
    salesRepId: "DEMO-REP-002",
    items: [{ productId: "DEMO-PROD-006", qty: 40 }],
    discountPercent: 28,
    stage: "REJECTED",
    approvalStage: "REJECTED",
    riskScore: 90,
    riskLevel: "HIGH",
    riskExplanation:
      "Discount is far above the sales representative's historical average and deal value threshold; flagged for rejection.",
    createdDaysAgo: 18,
    lastActivityDaysAgo: 6,
    upsellOpportunity: false,
    suggestedUpsellProducts: [],
    scenarioTags: ["rejected"],
  },
  {
    id: "DEMO-DEAL-015",
    customerId: "DEMO-CUST-003",
    salesRepId: "DEMO-REP-003",
    items: [{ productId: "DEMO-PROD-002", qty: 6 }],
    discountPercent: 9,
    stage: "OPEN",
    approvalStage: "NONE",
    riskScore: null,
    riskLevel: "LOW",
    riskExplanation: null,
    createdDaysAgo: 20,
    lastActivityDaysAgo: 12,
    upsellOpportunity: false,
    suggestedUpsellProducts: [],
    scenarioTags: ["stalled"],
  },
  {
    id: "DEMO-DEAL-016",
    customerId: "DEMO-CUST-004",
    salesRepId: "DEMO-REP-001",
    items: [{ productId: "DEMO-PROD-003", qty: 4 }],
    discountPercent: 6,
    stage: "OPEN",
    approvalStage: "NONE",
    riskScore: null,
    riskLevel: null,
    riskExplanation: null,
    createdDaysAgo: 3,
    lastActivityDaysAgo: 0,
    upsellOpportunity: false,
    suggestedUpsellProducts: [],
    scenarioTags: ["healthy"],
  },

  // --- New Deals 017 to 050: Expanding to 50 entities representing ALL stages ---

  // Deals 017 to 023: OPEN & Upsell Candidates across new customers
  {
    id: "DEMO-DEAL-017",
    customerId: "DEMO-CUST-005", // Tata Aerospace
    salesRepId: "DEMO-REP-001",
    items: [
      { productId: "DEMO-PROD-001", qty: 8 },
      { productId: "DEMO-PROD-007", qty: 4 },
    ],
    discountPercent: 8,
    stage: "OPEN",
    approvalStage: "NONE",
    riskScore: null,
    riskLevel: "LOW",
    riskExplanation: null,
    createdDaysAgo: 5,
    lastActivityDaysAgo: 1,
    upsellOpportunity: true,
    suggestedUpsellProducts: ["DEMO-PROD-008", "DEMO-PROD-005"],
    scenarioTags: ["healthy", "enterprise-hardware", "upsell-candidate"],
  },
  {
    id: "DEMO-DEAL-018",
    customerId: "DEMO-CUST-006", // MediHealth
    salesRepId: "DEMO-REP-003",
    items: [{ productId: "DEMO-PROD-002", qty: 14 }],
    discountPercent: 7,
    stage: "OPEN",
    approvalStage: "NONE",
    riskScore: null,
    riskLevel: null,
    riskExplanation: null,
    createdDaysAgo: 7,
    lastActivityDaysAgo: 2,
    upsellOpportunity: true,
    suggestedUpsellProducts: ["DEMO-PROD-006"],
    scenarioTags: ["healthy", "healthcare-fleet"],
  },
  {
    id: "DEMO-DEAL-019",
    customerId: "DEMO-CUST-007", // Bharat FinServ
    salesRepId: "DEMO-REP-002",
    items: [
      { productId: "DEMO-PROD-007", qty: 8 },
      { productId: "DEMO-PROD-008", qty: 5 },
    ],
    discountPercent: 14,
    stage: "OPEN",
    approvalStage: "NONE",
    riskScore: 25,
    riskLevel: "LOW",
    riskExplanation: null,
    createdDaysAgo: 11,
    lastActivityDaysAgo: 3,
    upsellOpportunity: false,
    suggestedUpsellProducts: [],
    scenarioTags: ["healthy", "fintech-infrastructure"],
  },
  {
    id: "DEMO-DEAL-020",
    customerId: "DEMO-CUST-008", // GreenAgro
    salesRepId: "DEMO-REP-004",
    items: [{ productId: "DEMO-PROD-003", qty: 15 }],
    discountPercent: 10,
    stage: "OPEN",
    approvalStage: "NONE",
    riskScore: null,
    riskLevel: null,
    riskExplanation: null,
    createdDaysAgo: 4,
    lastActivityDaysAgo: 1,
    upsellOpportunity: true,
    suggestedUpsellProducts: ["DEMO-PROD-005"],
    scenarioTags: ["healthy", "agritech-branch"],
  },
  {
    id: "DEMO-DEAL-021",
    customerId: "DEMO-CUST-009", // Zenith Edutech
    salesRepId: "DEMO-REP-001",
    items: [{ productId: "DEMO-PROD-002", qty: 25 }],
    discountPercent: 9,
    stage: "OPEN",
    approvalStage: "NONE",
    riskScore: null,
    riskLevel: "LOW",
    riskExplanation: null,
    createdDaysAgo: 9,
    lastActivityDaysAgo: 2,
    upsellOpportunity: true,
    suggestedUpsellProducts: ["DEMO-PROD-006"],
    scenarioTags: ["healthy", "edutech-lab"],
  },
  {
    id: "DEMO-DEAL-022",
    customerId: "DEMO-CUST-010", // OmniCloud
    salesRepId: "DEMO-REP-004",
    items: [
      { productId: "DEMO-PROD-001", qty: 6 },
      { productId: "DEMO-PROD-007", qty: 6 },
    ],
    discountPercent: 11,
    stage: "OPEN",
    approvalStage: "NONE",
    riskScore: null,
    riskLevel: null,
    riskExplanation: null,
    createdDaysAgo: 8,
    lastActivityDaysAgo: 0,
    upsellOpportunity: false,
    suggestedUpsellProducts: [],
    scenarioTags: ["healthy", "telecom-expansion"],
  },
  {
    id: "DEMO-DEAL-023",
    customerId: "DEMO-CUST-005", // Tata Aerospace
    salesRepId: "DEMO-REP-002",
    items: [{ productId: "DEMO-PROD-008", qty: 10 }],
    discountPercent: 13,
    stage: "OPEN",
    approvalStage: "NONE",
    riskScore: null,
    riskLevel: "LOW",
    riskExplanation: null,
    createdDaysAgo: 6,
    lastActivityDaysAgo: 1,
    upsellOpportunity: true,
    suggestedUpsellProducts: ["DEMO-PROD-005"],
    scenarioTags: ["healthy", "security-compliance"],
  },

  // Deals 024 to 030: PENDING_APPROVAL (SALES_MANAGER & FINANCE, varying risk)
  {
    id: "DEMO-DEAL-024",
    customerId: "DEMO-CUST-007", // Bharat FinServ
    salesRepId: "DEMO-REP-001",
    items: [
      { productId: "DEMO-PROD-001", qty: 12 },
      { productId: "DEMO-PROD-008", qty: 8 },
    ],
    discountPercent: 24,
    stage: "PENDING_APPROVAL",
    approvalStage: "SALES_MANAGER",
    riskScore: 78,
    riskLevel: "HIGH",
    riskExplanation:
      "Discount of 24% is significantly above rep's 7.8% historical baseline. Requires Sales VP sign-off.",
    createdDaysAgo: 5,
    lastActivityDaysAgo: 1,
    upsellOpportunity: false,
    suggestedUpsellProducts: [],
    scenarioTags: ["high-discount", "at-risk", "approval-required"],
  },
  {
    id: "DEMO-DEAL-025",
    customerId: "DEMO-CUST-006", // MediHealth
    salesRepId: "DEMO-REP-003",
    items: [{ productId: "DEMO-PROD-007", qty: 10 }],
    discountPercent: 19,
    stage: "PENDING_APPROVAL",
    approvalStage: "SALES_MANAGER",
    riskScore: 68,
    riskLevel: "MEDIUM",
    riskExplanation:
      "Rep's proposed discount of 19% exceeds regional benchmark threshold (15%).",
    createdDaysAgo: 7,
    lastActivityDaysAgo: 2,
    upsellOpportunity: false,
    suggestedUpsellProducts: [],
    scenarioTags: ["at-risk", "approval-required"],
  },
  {
    id: "DEMO-DEAL-026",
    customerId: "DEMO-CUST-010", // OmniCloud
    salesRepId: "DEMO-REP-004",
    items: [
      { productId: "DEMO-PROD-001", qty: 15 },
      { productId: "DEMO-PROD-007", qty: 10 },
    ],
    discountPercent: 12,
    stage: "PENDING_APPROVAL",
    approvalStage: "FINANCE",
    riskScore: 35,
    riskLevel: "LOW",
    riskExplanation:
      "High contract value (> ₹40 Lakhs) triggered mandatory Finance review; discount is healthy.",
    createdDaysAgo: 6,
    lastActivityDaysAgo: 1,
    upsellOpportunity: false,
    suggestedUpsellProducts: [],
    scenarioTags: ["healthy", "finance-approval", "large-value"],
  },
  {
    id: "DEMO-DEAL-027",
    customerId: "DEMO-CUST-005", // Tata Aerospace
    salesRepId: "DEMO-REP-002",
    items: [{ productId: "DEMO-PROD-002", qty: 45 }],
    discountPercent: 23,
    stage: "PENDING_APPROVAL",
    approvalStage: "SALES_MANAGER",
    riskScore: 72,
    riskLevel: "HIGH",
    riskExplanation:
      "Volume discount requested exceeds maximum standard schedule by 5%.",
    createdDaysAgo: 8,
    lastActivityDaysAgo: 2,
    upsellOpportunity: false,
    suggestedUpsellProducts: [],
    scenarioTags: ["at-risk", "high-discount"],
  },
  {
    id: "DEMO-DEAL-028",
    customerId: "DEMO-CUST-009", // Zenith
    salesRepId: "DEMO-REP-003",
    items: [
      { productId: "DEMO-PROD-003", qty: 20 },
      { productId: "DEMO-PROD-005", qty: 20 },
    ],
    discountPercent: 18,
    stage: "PENDING_APPROVAL",
    approvalStage: "SALES_MANAGER",
    riskScore: 62,
    riskLevel: "MEDIUM",
    riskExplanation:
      "Mid-market tier discount variance flagged by margin preservation rules.",
    createdDaysAgo: 4,
    lastActivityDaysAgo: 1,
    upsellOpportunity: false,
    suggestedUpsellProducts: [],
    scenarioTags: ["at-risk", "approval-required"],
  },
  {
    id: "DEMO-DEAL-029",
    customerId: "DEMO-CUST-001", // ABC Industries
    salesRepId: "DEMO-REP-004",
    items: [{ productId: "DEMO-PROD-007", qty: 15 }],
    discountPercent: 11,
    stage: "PENDING_APPROVAL",
    approvalStage: "FINANCE",
    riskScore: 28,
    riskLevel: "LOW",
    riskExplanation:
      "Routine enterprise credit and deferred payment terms sign-off.",
    createdDaysAgo: 3,
    lastActivityDaysAgo: 0,
    upsellOpportunity: false,
    suggestedUpsellProducts: [],
    scenarioTags: ["healthy", "finance-approval"],
  },
  {
    id: "DEMO-DEAL-030",
    customerId: "DEMO-CUST-008", // GreenAgro
    salesRepId: "DEMO-REP-001",
    items: [{ productId: "DEMO-PROD-002", qty: 18 }],
    discountPercent: 21,
    stage: "PENDING_APPROVAL",
    approvalStage: "SALES_MANAGER",
    riskScore: 75,
    riskLevel: "HIGH",
    riskExplanation:
      "Rep discount pattern anomaly: 21% discount compared to 7.8% rep target.",
    createdDaysAgo: 9,
    lastActivityDaysAgo: 2,
    upsellOpportunity: false,
    suggestedUpsellProducts: [],
    scenarioTags: ["at-risk", "high-discount"],
  },

  // Deals 031 to 037: FULFILLED (Multi-warehouse split completed deals)
  {
    id: "DEMO-DEAL-031",
    customerId: "DEMO-CUST-007", // Bharat FinServ
    salesRepId: "DEMO-REP-002",
    items: [{ productId: "DEMO-PROD-001", qty: 8 }],
    discountPercent: 10,
    stage: "FULFILLED",
    approvalStage: "APPROVED",
    riskScore: null,
    riskLevel: null,
    riskExplanation: null,
    createdDaysAgo: 35,
    lastActivityDaysAgo: 10,
    upsellOpportunity: false,
    suggestedUpsellProducts: [],
    warehouseSplit: [
      { warehouseId: "DEMO-WH-002", name: "Warehouse B", unitsAllocated: 5 },
      { warehouseId: "DEMO-WH-003", name: "Warehouse C", unitsAllocated: 3 },
    ],
    scenarioTags: ["fulfilled", "multi-warehouse"],
  },
  {
    id: "DEMO-DEAL-032",
    customerId: "DEMO-CUST-005", // Tata Aerospace
    salesRepId: "DEMO-REP-001",
    items: [{ productId: "DEMO-PROD-002", qty: 30 }],
    discountPercent: 8,
    stage: "FULFILLED",
    approvalStage: "APPROVED",
    riskScore: null,
    riskLevel: null,
    riskExplanation: null,
    createdDaysAgo: 45,
    lastActivityDaysAgo: 15,
    upsellOpportunity: false,
    suggestedUpsellProducts: [],
    warehouseSplit: [
      { warehouseId: "DEMO-WH-003", name: "Warehouse C", unitsAllocated: 20 },
      { warehouseId: "DEMO-WH-001", name: "Warehouse A", unitsAllocated: 10 },
    ],
    scenarioTags: ["fulfilled", "defense-delivery"],
  },
  {
    id: "DEMO-DEAL-033",
    customerId: "DEMO-CUST-010", // OmniCloud
    salesRepId: "DEMO-REP-004",
    items: [{ productId: "DEMO-PROD-007", qty: 25 }],
    discountPercent: 12,
    stage: "FULFILLED",
    approvalStage: "APPROVED",
    riskScore: null,
    riskLevel: null,
    riskExplanation: null,
    createdDaysAgo: 50,
    lastActivityDaysAgo: 18,
    upsellOpportunity: false,
    suggestedUpsellProducts: [],
    warehouseSplit: [
      { warehouseId: "DEMO-WH-004", name: "Warehouse D", unitsAllocated: 15 },
      { warehouseId: "DEMO-WH-002", name: "Warehouse B", unitsAllocated: 10 },
    ],
    scenarioTags: ["fulfilled", "hardware-switch"],
  },
  {
    id: "DEMO-DEAL-034",
    customerId: "DEMO-CUST-006", // MediHealth
    salesRepId: "DEMO-REP-003",
    items: [{ productId: "DEMO-PROD-003", qty: 50 }],
    discountPercent: 9,
    stage: "FULFILLED",
    approvalStage: "APPROVED",
    riskScore: null,
    riskLevel: null,
    riskExplanation: null,
    createdDaysAgo: 28,
    lastActivityDaysAgo: 8,
    upsellOpportunity: false,
    suggestedUpsellProducts: [],
    warehouseSplit: [
      { warehouseId: "DEMO-WH-004", name: "Warehouse D", unitsAllocated: 30 },
      { warehouseId: "DEMO-WH-001", name: "Warehouse A", unitsAllocated: 20 },
    ],
    scenarioTags: ["fulfilled", "hospital-devices"],
  },
  {
    id: "DEMO-DEAL-035",
    customerId: "DEMO-CUST-009", // Zenith
    salesRepId: "DEMO-REP-002",
    items: [{ productId: "DEMO-PROD-002", qty: 20 }],
    discountPercent: 11,
    stage: "FULFILLED",
    approvalStage: "APPROVED",
    riskScore: null,
    riskLevel: null,
    riskExplanation: null,
    createdDaysAgo: 32,
    lastActivityDaysAgo: 12,
    upsellOpportunity: false,
    suggestedUpsellProducts: [],
    warehouseSplit: [
      { warehouseId: "DEMO-WH-003", name: "Warehouse C", unitsAllocated: 20 },
    ],
    scenarioTags: ["fulfilled", "campus-hardware"],
  },
  {
    id: "DEMO-DEAL-036",
    customerId: "DEMO-CUST-008", // GreenAgro
    salesRepId: "DEMO-REP-004",
    items: [{ productId: "DEMO-PROD-001", qty: 4 }],
    discountPercent: 9,
    stage: "FULFILLED",
    approvalStage: "APPROVED",
    riskScore: null,
    riskLevel: null,
    riskExplanation: null,
    createdDaysAgo: 40,
    lastActivityDaysAgo: 22,
    upsellOpportunity: false,
    suggestedUpsellProducts: [],
    warehouseSplit: [
      { warehouseId: "DEMO-WH-002", name: "Warehouse B", unitsAllocated: 4 },
    ],
    scenarioTags: ["fulfilled", "datacenter-node"],
  },
  {
    id: "DEMO-DEAL-037",
    customerId: "DEMO-CUST-002", // XYZ Tech
    salesRepId: "DEMO-REP-001",
    items: [{ productId: "DEMO-PROD-007", qty: 12 }],
    discountPercent: 7,
    stage: "FULFILLED",
    approvalStage: "APPROVED",
    riskScore: null,
    riskLevel: null,
    riskExplanation: null,
    createdDaysAgo: 22,
    lastActivityDaysAgo: 5,
    upsellOpportunity: false,
    suggestedUpsellProducts: [],
    warehouseSplit: [
      { warehouseId: "DEMO-WH-003", name: "Warehouse C", unitsAllocated: 8 },
      { warehouseId: "DEMO-WH-004", name: "Warehouse D", unitsAllocated: 4 },
    ],
    scenarioTags: ["fulfilled", "network-upgrade"],
  },

  // Deals 038 to 043: SUBSCRIBED (Active SaaS/Cloud Recurring Contracts)
  {
    id: "DEMO-DEAL-038",
    customerId: "DEMO-CUST-007", // Bharat FinServ
    salesRepId: "DEMO-REP-004",
    items: [{ productId: "DEMO-PROD-004", qty: 250 }],
    discountPercent: 12,
    stage: "SUBSCRIBED",
    approvalStage: "APPROVED",
    riskScore: null,
    riskLevel: null,
    riskExplanation: null,
    createdDaysAgo: 60,
    lastActivityDaysAgo: 14,
    upsellOpportunity: false,
    suggestedUpsellProducts: [],
    subscription: {
      planName: "Enterprise Cloud Suite - Multi-Region",
      billingCycle: "ANNUAL",
      seats: 250,
      prorationNote: "Annual contract with automatic co-terming on seat additions.",
    },
    scenarioTags: ["subscription", "enterprise-saas", "annual-recurring"],
  },
  {
    id: "DEMO-DEAL-039",
    customerId: "DEMO-CUST-005", // Tata Aerospace
    salesRepId: "DEMO-REP-001",
    items: [{ productId: "DEMO-PROD-004", qty: 120 }],
    discountPercent: 8,
    stage: "SUBSCRIBED",
    approvalStage: "APPROVED",
    riskScore: null,
    riskLevel: null,
    riskExplanation: null,
    createdDaysAgo: 45,
    lastActivityDaysAgo: 7,
    upsellOpportunity: false,
    suggestedUpsellProducts: [],
    subscription: {
      planName: "Secure Cloud Core Dedicated",
      billingCycle: "ANNUAL",
      seats: 120,
      prorationNote: "Quarterly true-up for aerospace contractors.",
    },
    scenarioTags: ["subscription", "defense-cloud"],
  },
  {
    id: "DEMO-DEAL-040",
    customerId: "DEMO-CUST-006", // MediHealth
    salesRepId: "DEMO-REP-003",
    items: [{ productId: "DEMO-PROD-004", qty: 80 }],
    discountPercent: 10,
    stage: "SUBSCRIBED",
    approvalStage: "APPROVED",
    riskScore: null,
    riskLevel: null,
    riskExplanation: null,
    createdDaysAgo: 38,
    lastActivityDaysAgo: 6,
    upsellOpportunity: false,
    suggestedUpsellProducts: [],
    subscription: {
      planName: "HIPAA Compliant Health Cloud",
      billingCycle: "MONTHLY",
      seats: 80,
      prorationNote: "Monthly billing managed via automated billing orchestrator.",
    },
    scenarioTags: ["subscription", "healthcare-compliance"],
  },
  {
    id: "DEMO-DEAL-041",
    customerId: "DEMO-CUST-009", // Zenith Edutech
    salesRepId: "DEMO-REP-002",
    items: [{ productId: "DEMO-PROD-004", qty: 150 }],
    discountPercent: 15,
    stage: "SUBSCRIBED",
    approvalStage: "APPROVED",
    riskScore: null,
    riskLevel: null,
    riskExplanation: null,
    createdDaysAgo: 70,
    lastActivityDaysAgo: 16,
    upsellOpportunity: false,
    suggestedUpsellProducts: [],
    subscription: {
      planName: "Academic LMS Cloud Pro",
      billingCycle: "ANNUAL",
      seats: 150,
      prorationNote: "Term coincides with academic calendar.",
    },
    scenarioTags: ["subscription", "education-saas"],
  },
  {
    id: "DEMO-DEAL-042",
    customerId: "DEMO-CUST-010", // OmniCloud
    salesRepId: "DEMO-REP-004",
    items: [{ productId: "DEMO-PROD-004", qty: 95 }],
    discountPercent: 9,
    stage: "SUBSCRIBED",
    approvalStage: "APPROVED",
    riskScore: null,
    riskLevel: null,
    riskExplanation: null,
    createdDaysAgo: 55,
    lastActivityDaysAgo: 11,
    upsellOpportunity: false,
    suggestedUpsellProducts: [],
    subscription: {
      planName: "Telecom Ops Cloud Fleet",
      billingCycle: "MONTHLY",
      seats: 95,
      prorationNote: "Dynamic monthly seat bursting enabled.",
    },
    scenarioTags: ["subscription", "telecom-cloud"],
  },
  {
    id: "DEMO-DEAL-043",
    customerId: "DEMO-CUST-008", // GreenAgro
    salesRepId: "DEMO-REP-003",
    items: [{ productId: "DEMO-PROD-004", qty: 40 }],
    discountPercent: 6,
    stage: "SUBSCRIBED",
    approvalStage: "APPROVED",
    riskScore: null,
    riskLevel: null,
    riskExplanation: null,
    createdDaysAgo: 25,
    lastActivityDaysAgo: 4,
    upsellOpportunity: false,
    suggestedUpsellProducts: [],
    subscription: {
      planName: "AgriSensor Cloud Stream",
      billingCycle: "MONTHLY",
      seats: 40,
      prorationNote: "Standard prorated add-on license.",
    },
    scenarioTags: ["subscription", "iot-cloud"],
  },

  // Deals 044 to 047: STALLED DEALS (Inactive >= 5 days)
  {
    id: "DEMO-DEAL-044",
    customerId: "DEMO-CUST-006", // MediHealth
    salesRepId: "DEMO-REP-002",
    items: [{ productId: "DEMO-PROD-007", qty: 6 }],
    discountPercent: 12,
    stage: "OPEN",
    approvalStage: "NONE",
    riskScore: null,
    riskLevel: "LOW",
    riskExplanation: null,
    createdDaysAgo: 19,
    lastActivityDaysAgo: 9,
    upsellOpportunity: false,
    suggestedUpsellProducts: [],
    scenarioTags: ["stalled", "hardware-refresh"],
  },
  {
    id: "DEMO-DEAL-045",
    customerId: "DEMO-CUST-009", // Zenith
    salesRepId: "DEMO-REP-001",
    items: [
      { productId: "DEMO-PROD-002", qty: 12 },
      { productId: "DEMO-PROD-005", qty: 12 },
    ],
    discountPercent: 10,
    stage: "OPEN",
    approvalStage: "NONE",
    riskScore: null,
    riskLevel: null,
    riskExplanation: null,
    createdDaysAgo: 24,
    lastActivityDaysAgo: 14,
    upsellOpportunity: false,
    suggestedUpsellProducts: [],
    scenarioTags: ["stalled", "campus-procurement"],
  },
  {
    id: "DEMO-DEAL-046",
    customerId: "DEMO-CUST-008", // GreenAgro
    salesRepId: "DEMO-REP-003",
    items: [{ productId: "DEMO-PROD-001", qty: 3 }],
    discountPercent: 8,
    stage: "OPEN",
    approvalStage: "NONE",
    riskScore: null,
    riskLevel: "LOW",
    riskExplanation: null,
    createdDaysAgo: 28,
    lastActivityDaysAgo: 18,
    upsellOpportunity: false,
    suggestedUpsellProducts: [],
    scenarioTags: ["stalled", "cold-lead"],
  },
  {
    id: "DEMO-DEAL-047",
    customerId: "DEMO-CUST-010", // OmniCloud
    salesRepId: "DEMO-REP-004",
    items: [{ productId: "DEMO-PROD-008", qty: 6 }],
    discountPercent: 11,
    stage: "OPEN",
    approvalStage: "NONE",
    riskScore: null,
    riskLevel: null,
    riskExplanation: null,
    createdDaysAgo: 31,
    lastActivityDaysAgo: 21,
    upsellOpportunity: false,
    suggestedUpsellProducts: [],
    scenarioTags: ["stalled", "enterprise-security"],
  },

  // Deals 048 to 050: REJECTED (Closed Lost / Policy Violations)
  {
    id: "DEMO-DEAL-048",
    customerId: "DEMO-CUST-007", // Bharat FinServ
    salesRepId: "DEMO-REP-001",
    items: [{ productId: "DEMO-PROD-001", qty: 15 }],
    discountPercent: 32,
    stage: "REJECTED",
    approvalStage: "REJECTED",
    riskScore: 94,
    riskLevel: "HIGH",
    riskExplanation:
      "Discount of 32% violates minimum gross margin threshold (20%). Rejected by Finance Controller.",
    createdDaysAgo: 15,
    lastActivityDaysAgo: 5,
    upsellOpportunity: false,
    suggestedUpsellProducts: [],
    scenarioTags: ["rejected", "excessive-discount", "margin-violation"],
  },
  {
    id: "DEMO-DEAL-049",
    customerId: "DEMO-CUST-005", // Tata Aerospace
    salesRepId: "DEMO-REP-002",
    items: [{ productId: "DEMO-PROD-007", qty: 20 }],
    discountPercent: 29,
    stage: "REJECTED",
    approvalStage: "REJECTED",
    riskScore: 88,
    riskLevel: "HIGH",
    riskExplanation:
      "Requested SLA penalty indemnification clause not compliant with enterprise risk guidelines.",
    createdDaysAgo: 12,
    lastActivityDaysAgo: 4,
    upsellOpportunity: false,
    suggestedUpsellProducts: [],
    scenarioTags: ["rejected", "compliance-rejection"],
  },
  {
    id: "DEMO-DEAL-050",
    customerId: "DEMO-CUST-009", // Zenith Edutech
    salesRepId: "DEMO-REP-003",
    items: [{ productId: "DEMO-PROD-004", qty: 100 }],
    discountPercent: 35,
    stage: "REJECTED",
    approvalStage: "REJECTED",
    riskScore: 96,
    riskLevel: "HIGH",
    riskExplanation:
      "Unauthorized 35% non-profit educational discount rejected by Regional Sales Director.",
    createdDaysAgo: 10,
    lastActivityDaysAgo: 3,
    upsellOpportunity: false,
    suggestedUpsellProducts: [],
    scenarioTags: ["rejected", "unauthorized-discount"],
  },
];

const deals = raw.map((d) => ({
  id: d.id,
  customerId: d.customerId,
  salesRepId: d.salesRepId,
  products: lineItems(d.items),
  currency: "INR",
  grossValue: grossValue(d.items),
  discountPercent: d.discountPercent,
  value: netValue(d.items, d.discountPercent),
  stage: d.stage,
  approvalStage: d.approvalStage,
  riskScore: d.riskScore,
  riskLevel: d.riskLevel,
  riskExplanation: d.riskExplanation,
  createdDaysAgo: d.createdDaysAgo,
  lastActivityDaysAgo: d.lastActivityDaysAgo,
  upsellOpportunity: d.upsellOpportunity,
  suggestedUpsellProducts: (d.suggestedUpsellProducts || []).map((id) => ({
    productId: id,
    name: nameOf(id),
  })),
  ...(d.warehouseSplit ? { warehouseSplit: d.warehouseSplit } : {}),
  ...(d.subscription ? { subscription: d.subscription } : {}),
  scenarioTags: d.scenarioTags,
}));

const outPath = path.join(__dirname, "..", "src", "data", "deals.json");
fs.writeFileSync(outPath, JSON.stringify(deals, null, 2) + "\n");
console.log(`Wrote ${deals.length} deals to ${outPath}`);
